name: CI/CD

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    container:
      image: scailfin/madgraph5-amc-nlo:mg5_amc2.9.2
      options: --user root
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --quiet --no-cache-dir --ignore-installed --upgrade --editable .[test]
        python -m pip list
    - name: Test with pytest
      run: |
        python -m pytest -r sx
    - name: Test matrix element generation
      run: |
        cp -r $(madjax-config) /usr/local/MG5_aMC/PLUGIN/
        mg5_aMC --mode=madjax_me_gen examples/ee_to_mumuj.mg5
        ls -lhtra ee_to_mumuj_output/
    - name: Test matrix element evaluation
      run: |
        python examples/testME.py ee_to_mumuj_output
